# Generated by Django 5.0 on 2024-07-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circlemaker', '0002_userprofile_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
