# Generated by Django 5.0 on 2024-07-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circlemaker', '0003_userprofile_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize', models.CharField(max_length=200)),
            ],
        ),
    ]
