# Generated by Django 5.0 on 2024-07-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circlemaker', '0004_prize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='refralcoin',
            field=models.IntegerField(default=0),
        ),
    ]
